Controllers/DepartmentCourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Project_eng_ayman.Models;

namespace MVC_Project_eng_ayman.Controllers
{
    public class DepartmentCourseController : Controller
    { 
        ITIContext db = new ITIContext();
        public IActionResult showcourses(int id)
        {
            var model= db.Departments.Include(a=>a.Courses).FirstOrDefault(a=>a.DeptId==id);
            return View(model);
        }
        public IActionResult MangeCourse(int id)
        {
            var model = db.Departments.Include(a => a.Courses).FirstOrDefault(a => a.DeptId == id);
            var allcourses =db.Courses.ToList();
            var coursesindept = model.Courses;
            var coursesnotindept =allcourses.Except(coursesindept).ToList();
            ViewBag.coursenotindept =coursesnotindept;
            return View(model);
        }
        [HttpPost]
        public IActionResult MangeCourse(int id ,List<int> coursestoremove,List<int> coursestoadd)
        {
            Department dept = db.Departments.Include(a=>a.Courses).FirstOrDefault(a => a.DeptId == id);
            foreach(var item in coursestoremove)
            {
                Course c = db.Courses.FirstOrDefault(a => a.Id == item);
                dept.Courses.Remove(c);
            }
            db.SaveChanges();
            foreach (var item in coursestoadd)
            {
                Course c = db.Courses.FirstOrDefault(a => a.Id == item);
                dept.Courses.Add(c);
            }
            db.SaveChanges();
            return RedirectToAction("Index","Department");
        }

        public IActionResult addstudentdegree(int deptid ,int crsId)
        {
           var student= db.Students.Where(a => a.DeptNo == deptid).ToList();
            ViewBag.students = student;
            Department dept = db.Departments.Include(a => a.Students).FirstOrDefault(a => a.DeptId == deptid);
            Course course=db.Courses.FirstOrDefault(a=>a.Id == crsId);
            ViewBag.course = course;
            return View(dept);

        }
        [HttpPost]
        public IActionResult addstudentdegree(int deptid, int crsId,Dictionary<int,int>degree)
        {
            
            foreach(var item in degree)
            {
               var stdcrs= db.StudentCourses.FirstOrDefault(a => a.StudentId == item.Key && a.CrsId == crsId);
                if(stdcrs == null)
                { 
                    StudentCourse studentcourse = new StudentCourse() { StudentId = item.Key, CrsId = crsId, Degree = item.Value };

                   db.StudentCourses.Add(studentcourse);

                }
                else
                { 
                    stdcrs.Degree = item.Value;

                }
              
               
            }
            db.SaveChanges();
            return RedirectToAction("index", "department");

        }

    }
}

Views/DepartmentCourse/MangeCourse.cshtml
@model Department
@{
    Layout = null;
    SelectList coursesindept = new SelectList(Model.Courses, "Id", "Crs_Name");
    SelectList Coursesnotindept = new SelectList(ViewBag.coursenotindept, "Id", "Crs_Name");
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MangeCourse</title>
</head>
<body>
    <form method="post">
        <label>CoursesInDept</label>
        <select multiple asp-items="coursesindept" name="coursestoremove">

        </select>
        <label>CoursesNotInDept</label>
        <select multiple asp-items="Coursesnotindept" name="coursestoadd">

        </select>
        <input type="submit" value="Change Courses" />
    </form>
    
</body>
</html>

Views/DepartmentCourse/addstudentdegree.cshtml
@model Department
@{
    Layout = null;
    Course crs = ViewBag.course;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>addstudentdegree</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <h1>Department Name :@Model.DeptName</h1>
    <h1>Course Name :@crs.Crs_Name</h1>
    <form method="post" class="form-control">
        @foreach(var item in Model.Students)
        {
            <label>@item.Name</label>
            <input type="text" name="degree.@item.Id" /><br />
        }
        <input type="submit" value="add" class="btn btn-primary">
    </form>
</body>
</html>

Views/DepartmentCourse/showcourses.cshtml
@model Department
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>showcourses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div>
        @Model.DeptName Include Courses
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Course Name</th>
                <th>Course Duration</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Courses)
            {
                <tr>
                    <td>@item.Crs_Name</td>
                    <td>@item.Duration</td>
                    <td>
                        <a asp-action="addstudentdegree" asp-controller="DepartmentCourse" asp-route-deptid="@Model.DeptId" asp-route-crsId="@item.Id" class="btn btn-danger">Add Degree</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>

</body>

</html>